version: "2.1"

executors:
  docker-executor:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

workflows:
  main:
    jobs:
      - build-and-push

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t monitoring-api:latest .
      - run:
          name: Verify Docker Image Exists
          command: docker images | grep monitoring-api || { echo "Image not found"; exit 1; }
      - run:
          name: Extract Coverage Files from Docker Image
          command: |
            container_id=$(docker create monitoring-api:latest) && \
            docker cp $container_id:/app/coverage ./coverage && \
            docker rm -v $container_id
      - store_artifacts:
          path: ./coverage
          destination: coverage
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker tag monitoring-api:latest $DOCKER_USERNAME/monitoring-api:latest && \
            docker push $DOCKER_USERNAME/monitoring-api:latest

